### PR TITLE
added tutorial

### PR DESCRIPTION
**Pull request by Ephraim-nonso**

### CODE REVIEW

**Review by nonseodion — DISMISSED** [review]
Put it under Week 3

**Comment by Ephraim-nonso** [comment]
I was wondering as well. before I pushed. The folder I'm pushing to is named "Web3: Buil..". Not sure I'm supposed to push into any web3 folder.

**Comment by nonseodion** [comment]
That's true, before pushing, put it under Week 3 and name it, "Web2: ..."

**Comment by Ephraim-nonso** [comment]
I restructured the folder. Don't know if this folder arrangement is fine with you.

**Pull request merged**
